version: '3.7'

services:

    flask_app:
        build:
            context: ./flask_app
        image: flask_app
        restart: always
        expose:
            - "5000"

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - flask_app
        ports:
            - "8080:80"


